name: flutter_cube
description: A Flutter 3D widget that renders Wavefront's object files.
homepage: https://github.com/zesage/flutter_cube
publish_to: none

version: 0.1.0

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
